export { default as Main } from './Main/Main'
export { default as Burger } from './Burger/Burger'
export { default as Soup } from './Soup/Soup'
export { default as Dessert } from './Dessert/Dessert'
export { default as Header } from './Header/Header'
export { default as Aside } from './Aside/Aside'
